pipeline {
  agent any

  environment {
    APP_NAME    = "myapp"
    DOCKER_REPO = "parikshit298/azodha"
    AWS_REGION  = "ap-south-1"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
        script {
          env.GIT_SHA = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
          env.IMAGE   = "${DOCKER_REPO}:${GIT_SHA}"
        }
      }
    }

    stage('Build & Test') {
      steps {
        sh 'pip install -r requirements.txt || true'
        sh 'pytest || true'
      }
    }

    stage('Build Docker') {
      steps {
        sh "docker build -t ${IMAGE} ."
        sh "docker tag ${IMAGE} ${DOCKER_REPO}:latest"
      }
    }

    stage('Push to Docker Hub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
          sh '''
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker push ${IMAGE}
            docker push ${DOCKER_REPO}:latest
          '''
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG_FILE')]) {
          sh '''
            export KUBECONFIG=${KUBECONFIG_FILE}
            kubectl set image deployment/myapp myapp=${IMAGE} --record
            kubectl rollout status deployment/myapp
          '''
        }
      }
    }
  }
}

